# Generated by Django 2.1.7 on 2019-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='n_comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='n_pingback',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
